module.exports = {
    tutorialsSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
    userSidebar: [{type: 'autogenerated', dirName: 'user_docs'}],
    systemSidebar: [{type: 'autogenerated', dirName: 'system_docs'}],
  };